### ISSUE TITLE
Settings page reported as not working on community

### ISSUE THREAD

**Issue by linc** [galexrt/vanilla-steamsignin#1]
https://open.vanillaforums.com/discussion/32776/steam-sign-in-settings-page-not-working-resolved#latest

Includes a possible solution from R_J.

**Comment by galexrt** [comment]
Sorry for the late response!
I'm adding the fix right now, I'll comment when I fixed and released a new version.

**Comment by galexrt** [comment]
@linc I released a new version 1.1 with the fix.

https://open.vanillaforums.com/addon/galexsteamsignin-plugin-1.1
